apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-geoserver
spec:
  storageClassName: ""
  capacity:
    storage: 250G
  accessModes:
    - ReadWriteMany
  nfs:
   server: nfs-server.default.svc.cluster.local 
   path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-claim-geoserver
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250G
